version: '3.8'

services:
  statisticservicedb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: statistics_db
      POSTGRES_USER: YOUR_POSTGRES_USER
      POSTGRES_PASSWORD: YOUR_POSTGRES_PASSWORD
    ports:
      - "5433:5432"
    volumes:
      - statisticservicepgdata:/var/lib/postgresql/data
    networks:
      - microservices-net   # ← добавили

  statisticservice:
    build: .
    depends_on:
      - statisticservicedb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/statistics_db
      SPRING_DATASOURCE_USERNAME: YOUR_POSTGRES_USER
      SPRING_DATASOURCE_PASSWORD: YOUR_POSTGRES_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8080"
    restart: always
    networks:
      - microservices-net   # ← добавили

volumes:
  statisticservicepgdata:

networks:
  microservices-net:              # ← перезаписываем standard default
    external: true
