version: '3.8'

services:
  statisticservicedb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: statistics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wastedQ123
    ports:
      - "5435:5432"
    volumes:
      - statisticservicepgdata:/var/lib/postgresql/data
    networks:
      - microservices-net   # ← добавили

  statisticservice:
    container_name: statisticservice
    build: .
    depends_on:
      - statisticservicedb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://statisticservicedb:5432/statistics_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: wastedQ123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8080"
    restart: always
    networks:
      - microservices-net   # ← добавили

volumes:
  statisticservicepgdata:

networks:
  microservices-net:              # ← перезаписываем standard default
    external: true
