server:
  port: 8081

spring:
  application:
    name: statistics-service
  
  datasource:
    url: jdbc:postgresql://db:5432/statistics_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: wastedQ123

  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.example: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
